brew 'bash'
brew 'autojump'
brew 'openssl'
brew 'git'
brew 'git-lfs'
brew 'git-delta'
brew 'gh'
brew 'ack'
brew 'autoconf'
brew 'wxwidgets'
brew 'libxslt'
brew 'fop'
brew 'fswatch'
brew 'asdf'
brew 'neovim'

# For ASDF node
brew 'gpg'

cask 'firefox'
cask 'discord'
cask 'google-chrome'
cask 'google-drive'
cask 'imageoptim'
cask 'iterm2'
cask 'spotify'
cask 'languagetool-desktop'
cask 'slack'
cask 'docker-desktop'
cask 'gcloud-cli'
cask 'notion'
cask 'zoom'
cask '1password'
cask '1password/tap/1password-cli'
cask 'raycast'
cask 'steam'
cask 'telegram'
cask 'cursor'
cask 'zed'

brew 'mas'
mas 'The Unarchiver', id: 425424353
