#!/usr/bin/env bash

# Load utils
source ${HOME}/dotfiles/script/utils

###############################################################################
# OS X Customizations
###############################################################################

print_question 'Starting OS X Customizations...\n'

###############################################################################
# OS X others
###############################################################################

# Save screenshots in ~/Pictures/Screenshots folder
mkdir $HOME/Desktop/Screenshots
defaults write com.apple.screencapture location -string "$HOME/Desktop/Screenshots"

# Check for software updates daily, not just once per week
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

# Disable system-wide resume
defaults write com.apple.systempreferences NSQuitAlwaysKeepsWindows -bool false

# Turn off keyboard illumination when computer is not used for 30 seconds"
defaults write com.apple.BezelServices kDimTime -int 30

# Make keyboard cursor faster
defaults write -g InitialKeyRepeat -int 15
defaults write -g KeyRepeat -int 0.02

# Disable auto-correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# Show the main window when launching Activity Monitor
defaults write com.apple.ActivityMonitor OpenMainWindow -bool true

# Visualize CPU usage in the Activity Monitor Dock icon
defaults write com.apple.ActivityMonitor IconType -int 5

# Show all processes in Activity Monitor
defaults write com.apple.ActivityMonitor ShowCategory -int 0

# Sort Activity Monitor results by CPU usage
defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
defaults write com.apple.ActivityMonitor SortDirection -int 0

# Don't automatically open Photos.app when connecting iPhone/iTunes
defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true
defaults write com.apple.iTunes dontAutomaticallySyncIPods -bool true

# Disable automatic emoji substitution (i.e. use plain text smileys)
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticEmojiSubstitutionEnablediMessage" -bool false

# Only use UTF-8 in Terminal.app
defaults write com.apple.terminal StringEncodings -array 4

# Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
defaults write com.apple.screencapture type -string "png"

###############################################################################
# Finder
###############################################################################
# Disable window animations and Get Info animations
defaults write com.apple.finder DisableAllAnimations -bool true
# Show status bar
defaults write com.apple.finder ShowStatusBar -boolean true
# Show Path bar in Finder
defaults write com.apple.finder ShowPathbar -bool true
# Show sidebar on Finder
defaults write com.apple.finder ShowSidebar -bool true
# Use list view in all Finder windows by default
# Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"
# Group files by name
defaults write com.apple.finder FXPreferredGroupBy -string "Name"
# Enable spring loading for directories
defaults write NSGlobalDomain com.apple.springing.enabled -bool true
# Remove the spring loading delay for directories
defaults write NSGlobalDomain com.apple.springing.delay -float 0
# Disable disk image verification
defaults write com.apple.frameworks.diskimages skip-verify -bool true
defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true
# Automatically open a new Finder window when a volume is mounted
defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true
# Avoid creation of .DS_Store files on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
# Show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true
# Use current directory as default search scope in Finder
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
# Set default Finder path.
# For desktop, use `PfDe`.
# For other paths, use `PfLo` and `file:///full/path/here/`
defaults write com.apple.finder NewWindowTarget -string "PfHm"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/"
# Show the ~/Library folder
chflags nohidden ~/Library
###############################################################################
# Dock
###############################################################################
# Show indicator lights for open applications in the Dock
defaults write com.apple.dock show-process-indicators -bool true
# Set the icon size of Dock items to 48 pixels
defaults write com.apple.dock tilesize -int 36
# Set Dock zoom size
defaults write com.apple.dock magnification -int 0
# Don’t show Dashboard as a Space
defaults write com.apple.dock dashboard-in-overlay -bool true
# Don’t automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false
# Remove the animation when hiding/showing the Dock
defaults write com.apple.dock autohide-time-modifier -float 0
###############################################################################
# Kill affected applications
###############################################################################
for app in Safari Finder Dock SystemUIServer
do
  killall "$app" >/dev/null 2>&1
done
print_success 'OS X Customizations finished.\n'
