#!/bin/bash

link_files() {
  for i in $HOME/.dotfiles/*; do
    local base_name="$(basename $i)"
    [[ $base_name =~ ^(LICENSE|script|bin)$ ]] && continue
    echo "👉 Linking $base_name..."
    [[ -h $HOME/.$base_name ]] && rm $HOME/.$base_name
    ln -sf $i $HOME/.$base_name
  done

  echo "👉 Linking bin..."
  [[ -h $HOME/bin ]] && rm $HOME/bin
  ln -sf $HOME/.dotfiles/bin $HOME/bin
}

create_directories() {
  mkdir -p $HOME/projects/{personal,work}
  echo "👉 Creating directories on '~/projects'..."
}

# Install ohmyzsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

link_files
create_directories

$HOME/.dotfiles/script/osx_customization

echo "🎉  Done!"
