#!/bin/bash

link_files() {
  for i in $HOME/.dotfiles/*; do
    local base_name="$(basename $i)"
    [[ $base_name =~ ^(LICENSE|script)$ ]] && continue
    echo "👉 Linking $base_name..."
    ln -sf $i ~/.$base_name
  done
}

create_directories() {
  mkdir -p $HOME/projects/{personal,work}
  echo "👉 Creating directories on '~/projects'..."
}

link_files
create_directories

echo "🎉  Done!"
